sudo: false
dist: trusty
language: php
matrix:
  fast_finish: true
  include:
  - php: '5.3'
    dist: precise
  - php: '5.6'
    env: SNIFF=1
  - php: '7.0'
  - php: '7.2'
  - php: hhvm
  allow_failures:
  - php: hhvm
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git
  -b $PHPCS_BRANCH $PHPCS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git
  $SNIFFS_DIR/PHPCompatibility; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/bin/phpcs --config-set installed_paths
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
script:
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- if [[ "$SNIFF" == "1" ]]; then php . $PHPCS_DIR/bin/phpcs . -p -s -v -n --standard=./phpcs.ruleset.xml
  --extensions=php; fi
notifications:
  email: false
  slack:
    secure: mNmd88lhyT+Ag/VbjG3/gGw1K3S/EJIYQq6VoCKHfBgtzEil2hK5TDsH7ecrhp8s8vCOrJ1JXQe/UFzrlm2uIgIq+c1gV2p6QNSPF1OdcNV3fKKtlVj4XUIInVHkNR7ghOqdxkEx7CTomn0lEwAuR+GyGQtZnFMtFmEaNhkgZF6W6f41HGSFI0wcWoHly3LMBcNp0yK8WGyv/qbm/iysztQHZUVk3ejdH28nv3KLlZ5I6vNIBECdyJYmp7TkOvrKeBU03+484r4qvDbpKzoB1U7E4da3v/PcTXgVZk4Qr6Hn9DBh7nZ31ZJhizCl2scdXq3MCHUwe6edGweJ+bANOlgqZCu0MnibO2KSPL0UGWHFvl8EUCY1ij3G0jnuh4g71OOQZdn/9J/70KXqRBzt91VDWjB30nTJqDpp4hXeCW1cKj/E7GiT7x6IbI6DfcEkxb+IstUGJSLlIQJt8RgXflMRYWFz63WiX2BOTCf2Bxk8sW409Ay4my+NYVPmD0qcyxo23mMU3MIHk5EpMAw5kQvp6xBjJbncBjdd/MLEg/U3py/5MnerAZ5GfmpZ1z7RW5xvIUBuqR8aqXrGWwOML4Go4s9uuAdSriUK/ubqhSwfIPv2InMOul4SlaMxAaey5x8o0wXvIvewedqeFgTB5uUfaPHqRwe9dYs4DZAW8Wo=
